18-sessions-and-cookies/docoffice/config/routes.rb
Rails.application.routes.draw do
  resources :doctors
  resources :patients

  resources :users, only: [:create, :show]

  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  post "sessions", to: "sessions#create", as: "sessions"
  delete "sessions", to: "sessions#destroy", as: "logout"
end

18-sessions-and-cookies/docoffice/app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :patients

  def has_patients?
    patients.size > 0
  end

  validates :name, {
    length: { in: 2..50 },
    uniqueness: true
  }
  validates :skillz, length: { in: 3..140 }
  validate :is_polite

  def is_polite
    if self.skillz.include? 'bread'
      errors.add(:skillz, "no one should talk about bread")
    end
  end
end

18-sessions-and-cookies/docoffice/app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :doctor
end

18-sessions-and-cookies/docoffice/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

18-sessions-and-cookies/docoffice/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user

  def current_user
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
    else
      nil
    end
  end
  
  def logged_in?
    !!current_user
  end

  def authorized
    redirect_to login_path unless logged_in?
  end
end

18-sessions-and-cookies/docoffice/app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update]
  before_action :authorized, except: [:index]
  
  def index
    @doctors = Doctor.all
  end

  def show
    # byebug
    # if @doctor == nil
    #   redirect_to doctors_path
    # end
  end

  def new
    @doctor = Doctor.new
  end

  def create
    doc = Doctor.new(doctor_params)
    if doc.valid?
      doc.save
      redirect_to doc and return
    else
      flash[:errors] ||= []
      flash[:errors] = doc.errors.full_messages
      redirect_to new_doctor_path and return
    end
    redirect_to doctors_path
  end

  def edit
  end
  
  def update
    # doctor.update(params)
  end
  
  def delete
    doctor = Doctor.find(params[:id])
    doctor.destroy
  end

  private

  def doctor_params
    params.require(:doctor).permit(:name, :skillz)
  end

  def set_doctor
    @doctor = Doctor.find(params[:id])
  end
end

18-sessions-and-cookies/docoffice/app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = Patient.all
  end
  
  def show
  end

  def new
    @patient = Patient.new
    @doctors = Doctor.all
  end

  def create
    patient = Patient.create(patient_params)
    redirect_to patient_path(patient)
  end

  private

  def patient_params
    params.require(:patient).permit(:name, :condition, :doctor_id)
  end

end

18-sessions-and-cookies/docoffice/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      redirect_to login_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path
  end
end

18-sessions-and-cookies/docoffice/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      redirect_to @user
    else
      redirect_to new_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
  
end

18-sessions-and-cookies/docoffice/app/helpers/application_helper.rb
module ApplicationHelper
end

18-sessions-and-cookies/docoffice/app/helpers/users_helper.rb
module UsersHelper
end

18-sessions-and-cookies/docoffice/app/views/doctors/index.html.erb
<h1>
  doctors 👩‍⚕️👨‍⚕️
</h1>

<%= link_to 'create a new doc', new_doctor_path %>

<ul>
  <% @doctors.each do |doctor|  %>
    <li>
      <%= link_to doctor.name, doctor_path(doctor) %>
    </li>
  <% end %>
</ul>

18-sessions-and-cookies/docoffice/app/views/doctors/new.html.erb
<h1>
  create a new doctor 👩‍⚕️👨‍⚕️
</h1>
 
<%= form_for @doctor do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :skillz %>
  <%= f.text_field :skillz %>

  <%= f.submit %>
<% end %>

18-sessions-and-cookies/docoffice/app/views/doctors/show.html.erb
<h1>
  doctor <%= @doctor.name %> 👩‍⚕️👨‍⚕️
</h1>

<p>
  this doctor specializes in: <%= @doctor.skillz %>
</p>

<ul>
  <% if @doctor.has_patients? %>
    <% @doctor.patients.each do |patient| %>
      <li>
        <%= link_to "see #{patient.name}'s profile", patient %>
      </li>
    <% end %>
  <% else %>
    <p>
      This doctor has no patients
    <p>
  <% end  %>
</ul>

18-sessions-and-cookies/docoffice/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Docoffice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body> 

    <div>
      <% if !logged_in? %>
        <%= 'please log in:' %>
        <br>
        <%= link_to 'login', login_path %>
      <% else %>
        <%= 'hi ' + current_user.username %>
        <br>
        <%= link_to 'log out', logout_path, method: 'DELETE' %>
      <% end %>
    </div>

    <% flash[:errors] ||= []  %>

    <% if flash[:errors].size > 0 %>
      <% flash[:errors].each do |error| %>
        <p>
          <%= error %>
        </p>
      <% end %>
    <% end %>
   
    <h1>
      <%= link_to 'doc_app 🏥', doctors_path %>
    </h1>

    <%= yield %>
  </body>
</html>

18-sessions-and-cookies/docoffice/app/views/patients/index.html.erb
<h1>
  patients
</h1>

<%= link_to 'create a new patient', new_patient_path %>

<ul>
  <% @patients.each do |patient|  %>
    <li>
      <%= link_to patient.name, patient_path(patient) %>
    </li>
  <% end %>
</ul>

18-sessions-and-cookies/docoffice/app/views/patients/new.html.erb
<h1>
  create a new patient 🏥💰💰💰🚑👎
</h1>

<%= form_for @patient do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.label :condition %>
  <%= f.text_field :condition %>

  <%= f.label :doctor %>
  <%= f.collection_select :doctor_id, @doctors, :id, :name %>

  <%= f.submit %>
<% end %>
  
<%= link_to 'see all patients', patients_path %>

18-sessions-and-cookies/docoffice/app/views/patients/show.html.erb
<h1>
  patient <%= @patient.name %> 👩‍⚕️👨‍⚕️
</h1>

<p>
 this patient is treated by dr <%= @patient.doctor.name %>
</p>

<p>
  this patient's condition is <%= @patient.condition %>
</p>

<%= link_to 'all patients', patients_path %>

18-sessions-and-cookies/docoffice/app/views/users/new.html.erb
Sign up

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.text_field :password %>
  <%= f.submit %>
<% end %>

18-sessions-and-cookies/docoffice/app/views/users/show.html.erb
<%= @user.username %>'s page